### PR TITLE
feat: AutoGain filter

### LINKED ISSUE #14: Error (Xcode): Undefined symbol: _AVAudioSessionCategoryAmbient
**Description**

Errors when running to an iOS device:

```
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _AVAudioSessionCategoryAmbient

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryMultiRoute

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryPlayAndRecord

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryPlayback

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryRecord

Error (Xcode): Undefined symbol: _AVAudioSessionCategorySoloAmbient

Error (Xcode): Undefined symbol: _AVAudioSessionInterruptionNotification

Error (Xcode): Undefined symbol: _AVAudioSessionInterruptionTypeKey

Error (Xcode): Undefined symbol: _AVAudioSessionRouteChangeNotification

Error (Xcode): Undefined symbol: _AVAudioSessionRouteChangeReasonKey

Error (Xcode): Undefined symbol: _AudioComponentFindNext

Error (Xcode): Undefined symbol: _AudioComponentInstanceDispose

Error (Xcode): Undefined symbol: _AudioComponentInstanceNew

Error (Xcode): Undefined symbol: _AudioOutputUnitStart

Error (Xcode): Undefined symbol: _AudioOutputUnitStop

Error (Xcode): Undefined symbol: _AudioUnitAddPropertyListener

Error (Xcode): Undefined symbol: _AudioUnitGetProperty

Error (Xcode): Undefined symbol: _AudioUnitGetPropertyInfo

Error (Xcode): Undefined symbol: _AudioUnitInitialize

Error (Xcode): Undefined symbol: _AudioUnitRender

Error (Xcode): Undefined symbol: _AudioUnitSetProperty

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AVAudioSession
```

**Steps To Reproduce**

Just add the package and run on real ios device

### PR DESCRIPTION
**Pull request by alnitak**
## Description

New autoGain filter for #7 

- The `loopback.dart` example uses `flutter_soloud` to play audio back to the device from the microphone data stream. Please try it with a headset to prevent audio feedback.
- I do not have much experience in testing filter efficiency. To start please read the [filter doc](https://github.com/alnitak/flutter_recorder/blob/d3107e0125ac56ee18c0b79c0fb1368475cd9f31/lib/src/filters/filters.dart#L36) to know parameters meanings.
- ~No web support yet.~ Web supported.
- The `Echo Cancellation` #5 code is not yet ready and I don't know if it will be!

**Breaking change**:
- the `init` method is now async
- `FilterType` renamed to `RecorderFilterType`
- an [additional script](https://github.com/alnitak/flutter_recorder#web) must be added for the web platform. Now it looks like:
  ```
  <script src="assets/packages/flutter_recorder/web/libflutter_recorder_plugin.js" defer></script>
  <script src="assets/packages/flutter_recorder/web/init_recorder_module.dart.js" defer></script>
  ```

Closes #14 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [x] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by CillianMyles** [comment]
@alnitak thanks for the web support, I'm looking into it. I have added you plugin to internal builds and I hope to have some feedback for you next week! 👍

**Comment by CillianMyles** [comment]
I got an exception on web checking if a device was initialised:

```
TypeError: Cannot read properties of undefined (reading '_isInited')
packages/flutter_recorder/src/bindings/recorder_web.dart 178:38                              isDeviceInitialized
packages/flutter_recorder/src/flutter_recorder.dart 239:38                                   isDeviceInitialized
```

These checks work fine on IO platforms. Here is the code for ref:

```dart
  void _initRecordingDevice() {
    if (!_flutterRecorder.isDeviceInitialized()) {
      _flutterRecorder.init(
        format: PCMFormat.s16le,
        sampleRate: 16000,
        channels: RecorderChannels.mono,
      );
    }
    _startRecordingDevice();
  }

  void _startRecordingDevice() {
    if (!_flutterRecorder.isDeviceStarted()) {
      _flutterRecorder.start();
    }
    if (!_flutterRecorder.filters.autoGainFilter.isActive) {
      _flutterRecorder.filters.autoGainFilter.activate();
    }
  }

  void _stopRecordingDevice() {
    if (_flutterRecorder.filters.autoGainFilter.isActive) {
      _flutterRecorder.filters.autoGainFilter.deactivate();
    }
    if (_flutterRecorder.isDeviceStarted()) {
      _flutterRecorder.stop();
    }
  }

  void _disposeRecordingDevice() {
    _stopRecordingDevice();
    if (_flutterRecorder.isDeviceInitialized()) {
      _flutterRecorder.deinit();
    }
  }
```

**Comment by alnitak** [comment]
Thanks @CillianMyles, I forgot some checks!

FYI now the `init` doesn't throw when already initialized. It just displays a log message. Ie the `if (!_flutterRecorder.isDeviceStarted())` is no more needed.

Also, the logs are managed by `package:logging`, so you can initialize it like this:
```
import 'dart:developer' as dev;
import 'package:logging/logging.dart';

void main() async {
  // The `flutter_recorder` package logs everything
  // (from severe warnings to fine debug messages)
  // using the standard `package:logging`.
  // You can listen to the logs as shown below.
  Logger.root.level = kDebugMode ? Level.FINE : Level.INFO;
  Logger.root.onRecord.listen((record) {
    dev.log(
      record.message,
      time: record.time,
      level: record.level.value,
      name: record.loggerName,
      zone: record.zone,
      error: record.error,
      stackTrace: record.stackTrace,
    );
  });

  runApp(MyApp());
}
```

**Comment by alnitak** [comment]
> I am now running into a number of other errors:

I see. After changing the WASM module it must be initialized asynchronously somewhere. I chose to initialize it in the `init` method, so some other method calls don't work if the `init` has not yet been called.

I have to think about moving that initialization somewhere else! I'll update you

**Comment by alnitak** [comment]
The only safe way I found to initialize the WASM module is to do it in a JS script! So it should be added in the `index.html` alongside the recorder JS:
```
<script src="assets/packages/flutter_recorder/web/libflutter_recorder_plugin.js" defer></script>
<script src="assets/packages/flutter_recorder/web/init_recorder_module.dart.js" defer></script>
```

Two little breaking changes have been added also:
  - the `init` method is now async
  - `FilterType` renamed to `RecorderFilterType`

Hope it's all fine now and you can try the autogain also on the web and thanks for your patience!

**Comment by CillianMyles** [comment]
Thanks for the continued fixes 🙏 

Latest:

```
TypeError: Cannot read properties of undefined (reading '_createWorkerInWasm')
packages/flutter_recorder/src/bindings/recorder_web.dart 41:5
```

Which is happening during `init()`

**Comment by alnitak** [comment]
Ouch! That should not happen after adding `init_recorder_module.dart.js` in the `index.html`. That `.js` should expose all the methods, `_createWorkerInWasm` included!

With Firefox and Chrome, it doesn't happen to me. Maybe moving those `<script>` in the `<head>` instead of the `<body>` tag?

**Comment by CillianMyles** [comment]
Hey @alnitak 👋 

Happy new year 🎉 

Apologies for the delay in getting back to you here.

The automatic gain seems to be working well. I will come back to you if I find any issues.

Thanks 🙏

**Comment by alnitak** [comment]
I'm glad it worked, thanks for letting me know and happy new year to you too!

**Pull request merged**
